# CircleCI Configuration File
---
version: 2.1
jobs:
  unit_test:
    description: Run tests for formatting
    docker:
      - image: circleci/golang:1
    steps:
      - checkout
      - run:
          name: Run GO FMT on repo
          command: (( $(go fmt ./... | wc -c) == "0" ))
      - run:
          name: Unit tests with Go
          command: make test
  build:
    docker:
      - image: circleci/golang:1
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build container
          command: make container
  push_dev_image:
    context: dockerhub
    docker:
      - image: circleci/golang:1
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build image
          command: make container
      - run:
          name: Login
          command: echo $DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
      - run:
          name: Push image
          command: make push
workflows:
  default:
    jobs:
      - unit_test
      - build:
          requires:
            - unit_test
      - push_dev_image:
          requires:
            - build
          filters:
            branches:
              only:
                - master
